server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Vse poti preusmeri na index.html (react-router BrowserRouter)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache za staticne datoteke
    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
