name: Backend Test CI

on:
  push:
    branches: [ main ]

jobs:
  backend-unit-tests:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: SmartMailBox/backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install backend dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test
